volumes:
  node_modules:
    driver: local # Define the driver and options under the volume name

services:
  container:
    build: ./
    container_name: clinic-square-admin
    ports:
      - "4000:3000"
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    tty: true


